9 Sprint
SergeyGray/java-filmorate pull request #1
Opened 2022-10-09 14:38 UTC by SergeyGray

Fisrt try to merge 9 Sprint

2022-10-10 08:56 UTC, sergeymamonov requested changes
Описание коммитов должно быть подробно. Не должно быть несколько коммитов с одинаковым названием. В коллективной разработке, ваши коллеги будут видеть ваши коммиты, вам может потребоваться откатиться на какой-то коммит. Если они все называются одинаково, то будет сложно понять, на какой откатываться.

2022-10-10 08:56 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Вы же здесь не само приложение тестируете, а валидацию. Поэтому сделайте отдельный класс и перенесите тесты в этот класс.

2022-10-10 08:56 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		Throwable thrown = assertThrows(ValidationException.class,()->{
В каждом тесте создается юзер. Тогда это действие (создание корректного юзера) можно вынести в отдельный метод, который будет выполняться перед запуском каждого теста. А в тесте менять через сеттер какое либо поле у юзера на навалидное и уже с таким юзером проводить тест. С фильмами аналогично. И нужно разнести по классам. Это же разные сущности.
В тесте также необходимо проверить, верное ли сообщение выводится в ошибке.

2022-10-10 08:56 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		String description = "Россия - священная наша держава,\n" +
Если так делать строку определенной длины, то это сложно и легко ошибиться.
Можно сделать так "a".repeat(нужное количество раз).

2022-10-10 08:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film AddFilm(@Valid @RequestBody Film film) throws ValidationException, DataBaseException {
названия методов должны начинаться со строчной буквы (camelCase). Ниже аналогично.

2022-10-10 08:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/exception/DataBaseException.java
> +public class DataBaseException extends Exception{
Не самое подходящее название, так как из него непонятно, что за ошибка? База данных недоступна? Внутренняя ошибка базы данных? Или конфликт, такая-то сущность, уже есть в БД.

2022-10-10 08:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void setName(String name) throws ValidationException{
Сейчас метод по сути состоит из двух методов:
- валидации
- сеттера.
Это должны быть два отдельных метода.
Сеттеры, геттеры - если в них нет какой-то определенной логики, писать не нужно - для избавления от стандартных сеттеров и геттеров есть библиотека Lombok.

Валидацию можно написать самостоятельно (что сделано в сеттерах сейчас), либо сделать на аннотациях (некоторые аннотации уже стоят).
Если выберете написать валидацию, то в модели она точно быть не должна. В текущем спринте ее нужно разместить в контроллере. В следующих спринтах она переместиться в сервис.

2022-10-10 08:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        throw new ValidationException("Пустое название фильма");
Лучше точнее писать сообщения в ошибках, например, Название фильма должно содержать не менее ... символов.

2022-10-10 08:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +            throw new ValidationException("Слишком длинное описание фильма");
Лучше точнее писать сообщения в ошибках, например, Название фильма должно содержать не более ... символов.

2022-10-10 08:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +            throw new ValidationException("Некорректное время выхода фильма");
Лучше точнее писать сообщения в ошибках, например, Дата выхода фильма должна быть позже ...

2022-10-10 08:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(int id, String name, String description, LocalDate releaseDate, Integer duration)
Посмотрите библиотеку Lombok аннотации для конструкторов.

2022-10-10 21:22 UTC, SergeyGray commented
Убрал ручную валидацию, выполнил всё через аннотации, добавил пару пользовательских аннотаций для валидаторов 
Тесты так же изменил под них.
Но как выполнить замену полей name на login через пользовательские аннотации не понял. Это выполнил в контроллере.

2022-10-11 20:01 UTC, sergeymamonov approved these changes
Варианта как сделать с помощью аннотаций замену имени не подскажу. Как сейчас сделано, это хорошо.
Не делайте лишних веток, там, где они не нужны (см. пару замечаний по коду на это).

2022-10-11 20:01 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> getAllFilms(){
Лучше возвращать лист, а не коллекцию. Коллекция слишком общий интерфейс.

2022-10-11 20:01 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        }else {
В таком случае else не нужен. Если зайдете в if, дальше код исполняться не будет. А если не зайдете, то пойдете дальше по коду. А сейчас лишний else, лишнее смещение кода, лишние фигурные скобки.

2022-10-11 20:01 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        }else {
Старайтесь не делать лишних веток, когда можно обойтись без них. В данном случае можно обойтись без else.

2022-10-11 20:01 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getName() == null|| user.getName().isBlank()){
Лучше выделить в отдельный метод с информативным названием, чтобы было понятно, что это делается в рамках валидации.

2022-10-12 19:34 UTC, merged