Добавлена новая функциональность согласно 10 спринту
SergeyGray/java-filmorate pull request #3
Opened 2022-10-20 11:32 UTC by SergeyGray

Добавлены новые функциональности: добавления в друзья, а также система лайков.

2022-10-21 03:03 UTC, sergeymamonov requested changes

2022-10-21 03:03 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getFilm(@PathVariable int id){
Лучше делать между методами пустую строку. Так повысится читаемость кода.

2022-10-21 03:03 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      private HashMap <Integer,Film> films = new HashMap<>();
Проверьте, используются ли эта мапы и id? В другом контроллере аналогично.

2022-10-21 03:03 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService, FilmStorage filmStorage) {
Конструкторы можно не делать, а воспользоваться аннотациями Lombok.

2022-10-21 20:05 UTC, SergeyGray commented
Замечания исправлены

2022-10-22 11:50 UTC, sergeymamonov approved these changes

2022-10-22 11:50 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmStorage filmStorage;
filmStorage не должно быть в контроллере. Это уровень хранения данных. К уровню хранения данных должен обращаться сервис, а не контроллер.

2022-11-12 10:09 UTC, merged